
modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"

#issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory
modId="${modid}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
#displayURL="http://example.com/" #optional
#logoFile="examplemod.png" #optional
authors="${mod_authors}" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''${mod_description}'''

[[dependencies.${modid}]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${modid}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${modid}]]
    modId="curios"
    mandatory=true
    versionRange="[${curios_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${modid}]]
    modId="cloth_config"
    mandatory=true
    versionRange="[${cloth_config_api_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${modid}]]
    modId="bettercombat"
    mandatory=false
    versionRange="[${better_combat_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${modid}]]
    modId="ec_apotheosis_plugin"
    mandatory=false
    versionRange="[1.0.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${modid}]]
    modId="ec_create_plugin"
    mandatory=false
    versionRange="[1.0.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${modid}]]
    modId="ec_es_plugin"
    mandatory=false
    versionRange="[1.0.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${modid}]]
    modId="ec_ef_plugin"
    mandatory=false
    versionRange="[1.0.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${modid}]]
    modId="ec_aquaculture_plugin"
    mandatory=false
    versionRange="[1.0.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${modid}]]
    modId="ec_cje_plugin"
    mandatory=false
    versionRange="[1.0.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${modid}]]
    modId="ec_cjgn_plugin"
    mandatory=false
    versionRange="[1.0.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${modid}]]
    modId="ec_lec_plugin"
    mandatory=false
    versionRange="[1.0.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${modid}]]
    modId="ec_tf_plugin"
    mandatory=false
    versionRange="[1.0.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${modid}]]
modId="ec_an_plugin"
mandatory=false
versionRange="[1.0.1,)"
ordering="NONE"
side="BOTH"